- hosts: proxmox_labs:all
  become: false
  gather_facts: false
  tasks:

  - name: Create new vm with minimal options
    vars:
      ansible_python_interpreter: /usr/bin/python3
    proxmox_kvm:
      api_user: ansible@pam
      api_token_id: ansible-token
      api_token_secret: 7a4c9e2f-fede-417b-b0e8-d3cbaed5c5ad
      api_host: 192.168.102.10
      node: pvedemo1
      name: vmtest